print("=======================")
print("      MY PROFILE        ")
print("=======================")
print("Name      : Joshua")
print("Age       : 19")
print("Gender    : Male")
print("Course    : Computer Science")
print("College   : MVLU College")
print("Email     : joshuuaa2008@email.com")
print("Phone     : 8956321245")
print("=======================")
print("Hobbies   : playing Football, sleep all the time ")
print("Goal      : Become a Software Engineer")
print("=======================")
